<a href="https://colab.research.google.com/github/vivekanandainduri-nv/NV/blob/main/Exp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
df1SE =  pd.DataFrame({ 'jersey': [9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
                       'Score' : [22, 66, 31, 51, 71, 91, 56, 32, 52, 73, 92]})
df2SE =  pd.DataFrame({'jersey': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
                       'Score': [98, 93, 44, 77, 69, 56, 31, 53, 78, 93, 56, 77, 33, 56, 27]})

df1ML =  pd.DataFrame({ 'jersey': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
                       'Score' : [39, 49, 55, 77, 52, 86, 41, 77, 73, 51, 86, 82, 92, 23, 49]})
df2ML =  pd.DataFrame({'jersey': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
                       'Score': [93, 44, 78, 97, 87, 89, 39, 43, 88, 78]})

In [1]:
import pandas as pd
import numpy as np

In [5]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = pd.concat([dfML, dfSE], axis=1)
df

    jersey  Score  jersey  Score
0      1.0   39.0       9     22
1      3.0   49.0      11     66
2      5.0   55.0      13     31
3      7.0   77.0      15     51
4      9.0   52.0      17     71
5     11.0   86.0      19     91
6     13.0   41.0      21     56
7     15.0   77.0      23     32
8     17.0   73.0      25     52
9     19.0   51.0      27     73
10    21.0   86.0      29     92
11    23.0   82.0       2     98
12    25.0   92.0       4     93
13    27.0   23.0       6     44
14    29.0   49.0       8     77
15     2.0   93.0      10     69
16     4.0   44.0      12     56
17     6.0   78.0      14     31
18     8.0   97.0      16     53
19    10.0   87.0      18     78
20    12.0   89.0      20     93
21    14.0   39.0      22     56
22    16.0   43.0      24     77
23    18.0   88.0      26     33
24    20.0   78.0      28     56
25     NaN    NaN      30     27

In [6]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='inner')
df

Empty DataFrame
Columns: [jersey, Score]
Index: []

In [7]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='left')
df

    jersey  Score
0        9     22
1       11     66
2       13     31
3       15     51
4       17     71
5       19     91
6       21     56
7       23     32
8       25     52
9       27     73
10      29     92
11       2     98
12       4     93
13       6     44
14       8     77
15      10     69
16      12     56
17      14     31
18      16     53
19      18     78
20      20     93
21      22     56
22      24     77
23      26     33
24      28     56
25      30     27

In [8]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='right')
df

    jersey  Score
0        1     39
1        3     49
2        5     55
3        7     77
4        9     52
5       11     86
6       13     41
7       15     77
8       17     73
9       19     51
10      21     86
11      23     82
12      25     92
13      27     23
14      29     49
15       2     93
16       4     44
17       6     78
18       8     97
19      10     87
20      12     89
21      14     39
22      16     43
23      18     88
24      20     78

In [9]:
data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
dframe1
stacked = dframe1.stack()
stacked

stacked.unstack()

series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
frame2.unstack()

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN